services: #Container
  db:
    image: mysql
    container_name: mysql1
    networks:
      - beispiel-netzwerk
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testdb
    volumes:
      - db_mysql_save:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 5s
      retries: 5

  backend:
    build: ./
    container_name: mein-backend
    volumes:
    #Dieser Pfad muss bei euch angepasst werden
      # - /Users/suheibmarzouka/Desktop/24-01-ON/Workspaces/Node-Mysql-Docker-network:/app 
      - /app/node_modules
    networks:
      - beispiel-netzwerk
    ports:
      - 4000:5012
    depends_on:
      db:
        condition: service_healthy
        

volumes:
  db_mysql_save:
    
networks:
  beispiel-netzwerk:
    

# docker run -d --name mysql2 --network beispiel-netzwerk -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=testdb mysql
# docker run -d --network beispiel-netzwerk -p 4000:5012 --name mein-backend  node-backend